services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
      # Build development
      target: build-dev
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    # Run development stage
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
volumes:
  docker-nest-postgres:
